eureka:

  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin
