spring:
  application:
    name: product-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    hostname: localhost
server:
  port: 8087
 
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
      
